import { describe, it, expect, vi } from 'vitest';
import { renderHook, waitFor } from '@testing-library/react';
import { useEquipmentModulesQuery, useEquipmentInvertersQuery } from '../useEquipment';
import { createWrapper } from '@/test/utils';
import { mockModulesList, mockInvertersList } from '@/test/fixtures/equipment';
import { server } from '@/test/mocks/server';
import { http, HttpResponse, delay } from 'msw';

describe('useEquipment Hooks', () => {
    describe('useEquipmentModulesQuery', () => {
        it('should fetch all modules successfully and show loading state', async () => {
            // Delay response to ensure we catch loading state
            server.use(
                http.get('*/api/equipment/modules', async () => {
                    await delay(50);
                    return HttpResponse.json(mockModulesList);
                })
            );

            const { result } = renderHook(() => useEquipmentModulesQuery(), {
                wrapper: createWrapper()
            });

            // Explicit loading state
            expect(result.current.isLoading).toBe(true);

            await waitFor(() => expect(result.current.isSuccess).toBe(true));

            expect(result.current.data).toHaveLength(mockModulesList.length);
            expect(result.current.data![0].manufacturer).toBe(mockModulesList[0].manufacturer);
        });

        it('should filter modules by manufacturer', async () => {
            const { result } = renderHook(() => useEquipmentModulesQuery({ manufacturer: 'Test Solar' }), {
                wrapper: createWrapper()
            }); // New key generated by args

            await waitFor(() => expect(result.current.isSuccess).toBe(true));

            expect(result.current.data).toHaveLength(2);
            expect(result.current.data![0].manufacturer).toContain('Test Solar');
        });

        it('should handle error state correctly', async () => {
            server.use(
                http.get('*/api/equipment/modules', () => {
                    return new HttpResponse(null, { status: 500 });
                })
            );

            const { result } = renderHook(() => useEquipmentModulesQuery(), {
                wrapper: createWrapper()
            });

            await waitFor(() => expect(result.current.isError).toBe(true));
            expect(result.current.error).toBeDefined();
            // Optional: assert error message if your hook exposes it specifically
            // expect(result.current.error?.message).toContain('Request failed with status code 500');
        });
    });

    describe('useEquipmentInvertersQuery', () => {
        it('should fetch all inverters successfully and show loading state', async () => {
            server.use(
                http.get('*/api/equipment/inverters', async () => {
                    await delay(50);
                    return HttpResponse.json(mockInvertersList);
                })
            );

            const { result } = renderHook(() => useEquipmentInvertersQuery(), {
                wrapper: createWrapper()
            });

            expect(result.current.isLoading).toBe(true);

            await waitFor(() => expect(result.current.isSuccess).toBe(true));

            expect(result.current.data).toHaveLength(mockInvertersList.length);
            expect(result.current.data![0].manufacturer).toBe(mockInvertersList[0].manufacturer);
        });

        it('should filter inverters by manufacturer', async () => {
            const { result } = renderHook(() => useEquipmentInvertersQuery({ manufacturer: 'Test Energy' }), {
                wrapper: createWrapper()
            });

            await waitFor(() => expect(result.current.isSuccess).toBe(true));

            expect(result.current.data).toHaveLength(2);
            expect(result.current.data![0].manufacturer).toContain('Test Energy');
        });

        it('should handle error state correctly', async () => {
            server.use(
                http.get('*/api/equipment/inverters', () => {
                    return new HttpResponse(null, { status: 500 });
                })
            );

            const { result } = renderHook(() => useEquipmentInvertersQuery(), {
                wrapper: createWrapper()
            });

            await waitFor(() => expect(result.current.isError).toBe(true));
            expect(result.current.error).toBeDefined();
        });
    });
});
