"""add energy estimate retry fields

Revision ID: 323d4664204e
Revises: aa748ce719fc
Create Date: 2026-02-06 16:06:37.344520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '323d4664204e'
down_revision: Union[str, None] = 'aa748ce719fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('energy_estimates', sa.Column('retry_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('energy_estimates', sa.Column('last_retry_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('energy_estimates', 'last_retry_at')
    op.drop_column('energy_estimates', 'retry_count')
    # ### end Alembic commands ###

