"""add placement task tracking to site designs

Revision ID: aa748ce719fc
Revises: 01b88ee7b6fa
Create Date: 2026-02-05 20:09:20.941945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa748ce719fc'
down_revision: Union[str, None] = '01b88ee7b6fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_designs') as batch_op:
        batch_op.add_column(sa.Column('placement_task_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('placement_task_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('placement_task_error', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('placement_calculated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_designs') as batch_op:
        batch_op.drop_column('placement_calculated_at')
        batch_op.drop_column('placement_task_error')
        batch_op.drop_column('placement_task_status')
        batch_op.drop_column('placement_task_id')
    # ### end Alembic commands ###

